name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build
        # working-directory: project
        # shell: bash
        run: |
            west build app
        #   if [ "${{ runner.os }}" = "Windows" ]; then
        #     EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
        #   fi
        #   west twister -T app -v --inline-logs --integration -W $EXTRA_TWISTER_FLAGS

    #   - name: Twister Tests
    #     working-directory: project
    #     shell: bash
    #     run: |
    #       if [ "${{ runner.os }}" = "Windows" ]; then
    #         EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
    #       fi
    #       west twister -T tests --inline-logs --integration -W $EXTRA_TWISTER_FLAGS
